name: ukotka_hot_corners
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: any
  screen_retriever: any
  tray_manager: any
  flutter_lucide: any
  animations: any
  win32: any
  hotkey_manager: any
  launch_at_startup: any
  shared_preferences: any
  package_info_plus: any
  url_launcher: any
  flutter_localization: any
  intl: any
  ffi: any
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Using any for everything problematic to allow environment-specific resolution
# based on the SDK's internal pins (like intl or meta).

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
